### PR TITLE
Collapsible format for schedule

### PR DESCRIPTION
**Pull request by dontcallmedom**
This pull request brings a collapsible format for the schedule where we can add a list of session goals, presenters, scribe, etc. 

The content is aligned with what's currently on the gh-pages

### CODE REVIEW

**Comment by dontcallmedom** [comment]
@anssiko can you check that https://rawgit.com/w3c/vr-workshop/instructions/schedule.html works for you?

(we can probably tweak the style to make it more compact as in the current schedule; but at this point I would prefer merging something roughly ok to avoid further double maintenance of the agenda)

**Comment by anssiko** [comment]
@dontcallmedom Thanks! Looks fine on the latest versions of Chrome, Firefox, and Safari.

Also fine on iOS Safari, although on mobile I'd prefer a slightly narrower view. I'm wondering if we could remove the arrow that takes up some space?

Should probably run tidy on the markup.

**Comment by dontcallmedom** [comment]
what would you suggest instead of the arrow to indicate that (some) items are expandable?

as long as we're ok with the overall approach, I think we're better off merging and iterating once merged.

**Comment by anssiko** [comment]
Good to merge now, can iterate more when landed. Hover seems to work as a hint on non-touch devices of expandable.

Did you test on IE/Edge?-)

**Pull request merged**
